<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.qa.testScriptsSignup.TestCasesSignup">
        <methods>
          <include name="alreadyExistingEmailAddress"/>
          <include name="invalidPhonenumberWithCombinationOfCharactersNumbersSpecialSymbols"/>
          <include name="close"/>
          <include name="wrongConfirmPassword"/>
          <include name="Setup"/>
          <include name="incompleteConfirmPassword"/>
        </methods>
      </class> <!-- com.qa.testScriptsSignup.TestCasesSignup -->
      <class name="com.qa.testScriptsLogin.TestCasesLogin">
        <methods>
          <include name="Invalidusernamevalidpassword"/>
          <include name="nullpasswordvalidusername"/>
          <include name="Invalidusernameinvalidpassword"/>
          <include name="nullusernamevalidpassword"/>
          <include name="Invalidpasswordvalidusername"/>
          <include name="close"/>
          <include name="Setup"/>
        </methods>
      </class> <!-- com.qa.testScriptsLogin.TestCasesLogin -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
